/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.googlecode.netsentry;

public final class R {
    public static final class array {
        /**  Used in app/menu examples 
         */
        public static final int percentages=0x7f050000;
        /**  Used in app/menu examples 
         */
        public static final int percentages_values=0x7f050001;
        public static final int update_polling_intervals=0x7f050002;
        public static final int update_polling_intervals_values=0x7f050003;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int solid_gray_light=0x7f060002;
        public static final int solid_red=0x7f060000;
        public static final int solid_white=0x7f060003;
        public static final int solid_yellow=0x7f060001;
    }
    public static final class drawable {
        public static final int dotted_line_480px=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int icon_notification=0x7f020002;
        public static final int interface_type_3g=0x7f020003;
        public static final int interface_type_ethernet=0x7f020004;
        public static final int interface_type_unknown=0x7f020005;
        public static final int interface_type_wifi=0x7f020006;
        public static final int numberpicker_down_btn=0x7f020007;
        public static final int numberpicker_down_disabled=0x7f020008;
        public static final int numberpicker_down_disabled_focused=0x7f020009;
        public static final int numberpicker_down_normal=0x7f02000a;
        public static final int numberpicker_down_pressed=0x7f02000b;
        public static final int numberpicker_down_selected=0x7f02000c;
        public static final int numberpicker_input=0x7f02000d;
        public static final int numberpicker_input_disabled=0x7f02000e;
        public static final int numberpicker_input_normal=0x7f02000f;
        public static final int numberpicker_input_pressed=0x7f020010;
        public static final int numberpicker_input_selected=0x7f020011;
        public static final int numberpicker_up_btn=0x7f020012;
        public static final int numberpicker_up_disabled=0x7f020013;
        public static final int numberpicker_up_disabled_focused=0x7f020014;
        public static final int numberpicker_up_normal=0x7f020015;
        public static final int numberpicker_up_pressed=0x7f020016;
        public static final int numberpicker_up_selected=0x7f020017;
    }
    public static final class id {
        public static final int about_dialog_disclaimer=0x7f080000;
        public static final int buttons_spacer_left=0x7f08000f;
        public static final int data_picker=0x7f080001;
        public static final int data_picker_amount=0x7f080002;
        public static final int data_picker_dialog_info_text=0x7f080005;
        public static final int data_picker_dialog_picker=0x7f080004;
        public static final int data_picker_unit=0x7f080003;
        public static final int editor_button_reset_counters=0x7f080010;
        public static final int editor_button_set_transmission_limit=0x7f08000e;
        public static final int editor_data_received=0x7f08000a;
        public static final int editor_data_sent=0x7f08000b;
        public static final int editor_data_total=0x7f08000c;
        public static final int editor_image_interface_type=0x7f080008;
        public static final int editor_interface_alias=0x7f080006;
        public static final int editor_interface_name=0x7f080007;
        public static final int editor_spinner_auto_reset=0x7f080011;
        public static final int editor_transmission_limit=0x7f08000d;
        public static final int info_size_dots=0x7f080009;
        public static final int interfaceList_Item_counter=0x7f080014;
        public static final int interfaceList_Item_image_interfaceType=0x7f080012;
        public static final int interfaceList_Item_interfaceAlias=0x7f080013;
        public static final int interfaceList_Item_lastReset=0x7f080015;
        public static final int interfaceList_Item_lastReset_value=0x7f080016;
        public static final int number_picker_button_decrement=0x7f080019;
        public static final int number_picker_button_increment=0x7f080017;
        public static final int number_picker_input=0x7f080018;
        public static final int percentage_picker=0x7f08001a;
        public static final int percentage_picker_percentage=0x7f08001b;
    }
    public static final class layout {
        public static final int about_dialog=0x7f030000;
        public static final int data_picker=0x7f030001;
        public static final int data_picker_dialog=0x7f030002;
        public static final int interfacestats_editor=0x7f030003;
        public static final int interfacestats_list_item=0x7f030004;
        public static final int number_picker=0x7f030005;
        public static final int percentage_picker=0x7f030006;
    }
    public static final class string {
        public static final int about_dialog_disclaimer=0x7f07002c;
        public static final int about_dialog_text=0x7f07002d;
        /**  about dialog 
         */
        public static final int about_dialog_title=0x7f07002b;
        public static final int app_name=0x7f070000;
        public static final int button_close=0x7f070005;
        public static final int dialog_transmission_limit_title=0x7f070006;
        public static final int editor_auto_reset_description=0x7f07001d;
        public static final int editor_button_reset_counters=0x7f07001b;
        public static final int editor_button_set_transmission_limit=0x7f07001a;
        public static final int editor_category_data=0x7f070012;
        public static final int editor_category_reset=0x7f070013;
        public static final int editor_cron_every_day=0x7f070020;
        public static final int editor_cron_every_month=0x7f070021;
        public static final int editor_cron_not_scheduled=0x7f07001f;
        public static final int editor_dialog_reset_counters=0x7f07001c;
        public static final int editor_label_data_received=0x7f070015;
        public static final int editor_label_data_sent=0x7f070016;
        public static final int editor_label_data_total=0x7f070017;
        public static final int editor_label_transmission_limit=0x7f070018;
        public static final int editor_show_in_list=0x7f070014;
        public static final int editor_spinner_auto_reset=0x7f07001e;
        /**  item editor 
         */
        public static final int editor_title=0x7f070011;
        public static final int editor_transmission_limit_info_text=0x7f070019;
        public static final int infinity_sign=0x7f070007;
        /**  interface list 
         */
        public static final int list_item_last_reset=0x7f070010;
        public static final int menu_item_about=0x7f070003;
        public static final int menu_item_edit=0x7f070002;
        public static final int menu_item_preferences=0x7f070004;
        /**  general 
         */
        public static final int menu_item_reset_counters=0x7f070001;
        public static final int notification_usage_level_high=0x7f07000f;
        public static final int notification_usage_level_high_title=0x7f07000e;
        public static final int notification_usage_level_medium=0x7f07000d;
        /**  notification 
         */
        public static final int notification_usage_level_medium_title=0x7f07000c;
        /**  preferences view 
         */
        public static final int preferences_activity_title=0x7f070022;
        public static final int preferences_category_automatic_update=0x7f070024;
        public static final int preferences_category_usage_thresholds=0x7f070023;
        public static final int preferences_update_interval_summary=0x7f070026;
        public static final int preferences_update_interval_title=0x7f070025;
        public static final int preferences_usage_high_summary=0x7f07002a;
        public static final int preferences_usage_high_title=0x7f070029;
        public static final int preferences_usage_medium_summary=0x7f070028;
        public static final int preferences_usage_medium_title=0x7f070027;
        public static final int provider_interface_alias_3g=0x7f070009;
        public static final int provider_interface_alias_ethernet=0x7f07000a;
        public static final int provider_interface_alias_loopback=0x7f07000b;
        /**  interface stats provider 
         */
        public static final int provider_interface_alias_wifi=0x7f070008;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
